[package]
name = "nest"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.101"
wasm-bindgen-futures = "0.4.51"
web-sys = { version = "0.3.78", features = ["Window", "Document", "HtmlElement", "EventTarget"] }
